dist: xenial
language: python
python:
  - 3.7

install:
  - pip install nbfancy 

script:
  - cd Final
  - nbfancy configure -y all_magic 
  - nbfancy render
  - nbfancy html

deploy:
  provider: pages
  repo: djstock/MPhys-Project
  target-branch: gh-pages
  local-dir: Final/html
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
    python: 3.7
